### ISSUE TITLE
Editing Readme file

### ISSUE THREAD

**Issue by Rahul-3000** [WikipediaLibrary/TWLight#523]
Hey folks!
Today I was setting up the environment for TWLight but I faced some issue with docker. Though I had it on my system but still due to some issue it wasn't showing. So instead of keeping Get docker Cant we add commands there so that a newbie like me dont find trouble.
If yes I would add it.

**Comment by Samwalton9** [comment]
Hi!

The problem with adding the exact commands is that they vary based on your setup (i.e. your operating system). It's better for us to link to the Docker documentation where you can find precisely the instructions you're looking for. 

_That said_, I've updated the Docker link to https://docs.docker.com/get-docker/, because docker.com wasn't a helpful place to send people. Thanks for the suggestion!
