### ISSUE TITLE
Allow login everywhere

### ISSUE THREAD

**Issue by Discostu36** [WikipediaLibrary/TWLight#932]
Logging in for using the project should be possible in the header area of every page, not only on the homepage. I wondered why I couldn't click the application button because it was not clear to me that I need to be logged in but wasn't .

**Comment by Samwalton9** [comment]
Thanks for the suggestion, this makes sense. I've filed https://phabricator.wikimedia.org/T299638 (and will close this ticket, since we don't track issues here).

Just to clarify - which page were you on, and how did you navigate there while logged out? This will help us make sure the library UX makes sense.

**Comment by Discostu36** [comment]
> Just to clarify - which page were you on, and how did you navigate there while logged out? This will help us make sure the library UX makes sense.

Just checked in my browser history: I was at [this page on German Wikipedia](https://de.wikipedia.org/wiki/Wikipedia:F%C3%B6rderung/The_Wikipedia_Library/%C3%9Cbersicht) and from there navigated to [a partner I was interested in](https://wikipedialibrary.wmflabs.org/partners/60/).

**Comment by Samwalton9** [comment]
Ahh, OK, thanks :)
